src/components/uploader/OperationUploader.tsx
上传文件不存在 minimum_required 字段时，自动进行补全 #8;
levelId regex fix
fix #8
=> fix(uploader): operation minimum_required missing and stage_name regex

src/components/uploader/OperationUploader.tsx
* operation['doc'] might be undefined
* regex may fail on main stages
=> fix(uploader): operation patch error

src/apis/query.ts, src/components/OperationList.tsx, src/components/Operations.tsx, src/components/Suspensable.tsx
=> feat: search operation by ID

src/components/viewer/OperationViewer.tsx, src/layouts/AppLayout.tsx, src/main.tsx, src/pages/index.tsx, src/styles/global.css
=> feat: add container to OperationList, improve scrollbar behavior & fix rating error message

src/components/editor/action/EditorActionAdd.tsx, src/components/editor/action/EditorActionDelay.tsx, src/components/editor/action/EditorActionExecPredicate.tsx, src/components/editor/action/EditorActionOperatorDirection.tsx, src/components/editor/action/EditorActionOperatorLocation.tsx, src/components/editor/action/validation.ts, src/components/editor/operator/EditorOperator.tsx, src/components/editor/operator/EditorOperatorSkillUsage.tsx, src/models/copilot.schema.ts
往编辑器里加入了所有动作的面板，以及 cooling 字段 （#34）
=> feat(editor): action panels

src/components/dnd.tsx, src/components/editor/action/EditorActionAdd.tsx, src/components/editor/action/EditorActionDelay.tsx, src/components/editor/action/EditorActionExecPredicate.tsx, src/components/editor/action/EditorActionItem.tsx, src/components/editor/action/EditorActionOperatorDirection.tsx, src/components/editor/action/EditorActionOperatorLocation.tsx, src/components/editor/action/EditorActions.tsx, src/components/editor/operator/EditorOperator.tsx, src/components/editor/operator/EditorOperatorItem.tsx, src/components/editor/operator/EditorOperatorSkillUsage.tsx, src/components/editor/operator/EditorPerformer.tsx, src/components/viewer/ViewerActions.tsx, src/models/operator.ts, src/utils/times.ts
- Implemented UI of action cards based on those in operation viewer
bugfixes:
- properly handle dragging cancellation for operators
- operators being swapped when dragged
- submitted action containing properties of other types
- copilotdocv1 type in viwer actions (@martinwang2002)
=> feat(editor): action cards

src/components/HelperText.tsx, src/components/editor/CardOptions.tsx, src/components/editor/OperationEditor.tsx, src/components/editor/action/EditorActionAdd.tsx, src/components/editor/action/EditorActionItem.tsx, src/components/editor/action/EditorActionTypeSelect.tsx, src/components/editor/action/EditorActions.tsx, src/components/editor/operator/EditorGroupItem.tsx, src/components/editor/operator/EditorOperatorItem.tsx, src/components/editor/operator/EditorPerformer.tsx, src/components/editor/operator/EditorPerformerAdd.tsx, src/components/editor/operator/EditorPerformerGroup.tsx, src/components/editor/operator/EditorPerformerOperator.tsx, src/components/editor/sanitizer.ts, src/styles/blueprint.less, src/types.d.ts, src/utils/useEditableFields.ts
支持编辑已添加的动作/干员/干员组
使用方法：
1. 点击 item 上的编辑按钮进入编辑模式（再次点击可以取消）
2. 在 form 中修改内容后，点击保存
另外将动作 item 上的删除按钮应用到了干员/干员组 item 上，使其风格一致
=> feat(editor): editing actions/performers

src/models/operator.ts
=> chore: 修改信息打印颜色选项

src/components/editor/CardOptions.tsx, src/components/editor/OperationEditor.tsx, src/components/editor/action/EditorActionAdd.tsx, src/components/editor/action/EditorActionItem.tsx, src/components/editor/action/EditorActionOperatorLocation.tsx, src/components/editor/action/EditorActions.tsx, src/components/editor/operator/EditorOperator.tsx, src/components/editor/operator/EditorPerformer.tsx, src/components/editor/operator/EditorPerformerGroup.tsx, src/components/editor/operator/EditorPerformerOperator.tsx, src/styles/blueprint.less
- fix: 修复颜色错误
- fix #67
- fix(editor): uncontrolled inputs
- fix(editor): textarea shrinking on input
- fix(editor): duplicating actions （这个打错了应该是 feat）
=> fix(editor): form behaviors

src/components/editor/OperationEditor.tsx, src/components/entity/EDifficulty.tsx, src/models/copilot.schema.ts
=> feat(editor): difficulty picker

src/components/OperatorSelect.tsx
fix  : [https://github.com/MaaAssistantArknights/maa-copilot-frontend/issues/90](url)
让展示框默认大小变大了一点（
=> "fix: 干员搜索框滚动条出现两个的样式问题"

src/components/editor/operator/EditorPerformerOperator.tsx
=> fix: 选择干员时默认一技能但是skill字段为空的问题

package.json, src/App.tsx, src/apis/arknights.ts, src/components/editor/EditorIntegerInput.tsx, src/components/editor/NumericInput2.tsx, src/components/editor/OperationEditor.tsx, src/components/editor/action/EditorActionAdd.tsx, src/components/editor/action/EditorActionDelay.tsx, src/components/editor/action/EditorActionExecPredicate.tsx, src/components/editor/action/EditorActionItem.tsx, src/components/editor/source/SourceEditorHeader.tsx, src/components/editor/validation.ts, src/components/viewer/ViewerActions.tsx, src/models/copilot.schema.json, src/models/copilot.schema.ts, src/models/types.ts, src/pages/create.tsx, src/utils/swr-cache.ts, yarn.lock
- feat: cache levels with localStorage (#98)
- feat(editor): use operation title as download filename (#98)
- feat: support "costs" field (#84)
- feat(editor): ensure action type that follows BulletTime (#84)
- feat(editor): support negative "costChanges"
=> Schema update & feature improvements

package.json, src/apis/auth.ts, src/components/AccountManager.tsx, src/components/Effects.tsx, src/components/account/AuthFormShared.tsx, src/components/account/EditDialog.tsx, src/components/account/LoginPanel.tsx, src/components/account/ResetPasswordDialog.tsx, src/components/viewer/OperationViewer.tsx, src/store/auth.ts, src/utils/fetcher.ts, yarn.lock
- feat: editing user info and password
- feat: resetting password (#101)
- feat: show rating buttons without logging in (#46)
- feat: use refresh token
=> Account features

src/pages/index.tsx
=> chore: announcement for server

src/pages/index.tsx
=> docs: 更新后端地址

src/components/editor/action/EditorActionAdd.tsx, src/components/editor/action/EditorActionDistance.tsx, src/components/editor/action/EditorActionItem.tsx, src/models/copilot.schema.json, src/models/copilot.schema.ts, src/models/types.ts
=> feat: "MoveCamera" action

README.md, src/components/editor/floatingMap/FloatingMap.tsx, src/pages/index.tsx
- 修复左下角通知被小地图遮挡的问题
- 更新文档及招人信息
=> fix: toasts being covered by floating map

src/components/BackToTop.tsx, src/layouts/AppLayout.tsx
=> feat: add backToTop button

src/components/OperationCard.tsx, src/components/viewer/OperationRating.tsx, src/components/viewer/OperationViewer.tsx, src/models/operation.ts
- fix: downloaded operation is not snake-cased
- fix: mismatching operation.notEnoughRating (#133)
- feat: show rating view even if notEnoughRating=true
=> fix: downloaded operation is not snake-cased

src/utils/swr-cache.ts
线上出现了关卡数据无法加载的问题，原因是：
1. 由于某种原因，比如关卡加载完成之前离开页面，导致关卡缓存里存入了无效的数据
2. 在每次进入页面校验缓存时会丢弃掉无效的缓存，把关卡数据设为 `undefined`
3. 丢弃的动作发生在 SWR 发出请求之后，这样 SWR 会认为稍后获取到的数据已经 stale
4. 由于已经 stale，SWR 丢掉获取到的数据，并尝试发送新的请求，但是 /level 的 `dedupingInterval` 设为一天，所以请求不会发出
5. 关卡数据没有更新，永远是 `undefined`
解决方式是用 `useRef` 代替 `useEffect` 保证在调用 `useSWR` 之前就把缓存丢掉
=> fix: broken levels cache

src/components/editor/action/EditorActionAdd.tsx, src/components/editor/action/EditorActionModule.tsx
=> feat: 作业编辑器动作序列展开 条件可折叠

src/components/editor/action/EditorActionAdd.tsx, src/components/viewer/OperationRating.tsx, src/models/operation.ts
关联isuue：https://github.com/MaaAssistantArknights/maa-copilot-frontend/issues/136
效果如图：
需要鼠标悬浮到文字位置上才会显示，是不是可以继续改进一下？
=> feat: 为作业详情页面增加评价数量

src/apis/auth.ts, src/components/account/AuthFormShared.tsx, src/components/account/EditDialog.tsx, src/components/account/RegisterPanel.tsx
=> fix: 修改了用户注册相关 #231

src/components/editor/action/EditorActionAdd.tsx, src/components/editor/operator/EditorOperator.tsx, src/styles/blueprint.less
=> ✨ feat(EditorOperatorName): 调整动作序列中的干员选择列表排序，已选择的排在前面

src/components/OperationCard.tsx, src/components/OperationList.tsx, src/components/Operations.tsx, src/components/entity/ELevel.tsx, src/store/pref.ts
=> refactor: index page layout and OperationCard layout

src/components/editor/operator/sheet/SheetOperatorSkillAbout.tsx
调整了一下sheet中tooltip的文字提示样式，让其能自适应暗黑主题。
但其实好像有很多这种地方在暗黑模式下都有一点小问题，猜测是tooltip组件的锅，如图：
那一块代码不是很熟，所以暂时没有改动
=> fix: style of font in sheet fixed

src/components/editor/action/EditorActionAdd.tsx
针对动作序列区域参数过多导致的额外滑动页面问题，新增添加按钮，简化用户操作
=> feat: add an extra button for easy access

index.html
=> feat: add description and keywords

src/styles/blueprint.less
=> style: remove unnecessary darkmode overwriting

src/components/ActionCard.tsx, src/components/FactItem.tsx, src/components/HelperText.tsx, src/components/OperationCard.tsx, src/components/drawer/NavAside.tsx, src/components/entity/EDifficulty.tsx, src/components/entity/ELevel.tsx, src/components/viewer/OperationRating.tsx, src/components/viewer/OperationSetViewer.tsx, src/components/viewer/OperationViewer.tsx, src/layouts/AppLayout.tsx, src/pages/index.tsx, src/styles/blueprint.less
=> feat: add dark theme config #310

src/pages/index.tsx
=> feat: pages index sticky

index.html, src/components/AccountManager.tsx, src/components/viewer/OperationSetViewer.tsx, src/components/viewer/OperationViewer.tsx, src/layouts/AppLayout.tsx
ZOOT 也好 PRTS 也好，总之先不叫 MAA Copilot 了
=> chore: rename website

src/components/ActionCard.tsx
I always forgot about this one.
=> fix: i18n for operators in action sequence.
